CoderGirl_StLouisSites/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoderGirl_StLouisSites.Models
{
    public class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<LocationRateAndReview> RateAndReviews { get; set; }
        public string StreetAddress { get; set; }
        public string County { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
    }
}

CoderGirl_StLouisSites/ViewModels/Locations/LocationCreateViewModel.cs
using CoderGirl_StLouisSites.Data;
using CoderGirl_StLouisSites.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoderGirl_StLouisSites.ViewModels.Locations
{
    public class LocationCreateViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please give the description between 2 to 200 characters")]
        [MinLength(2)][StringLength(200)]
        public string Description { get; set; }
        public string StreetAddress { get; set; }
        [Required]
        public string County { get; set; }
        [Required(ErrorMessage = "ZipCode is required")]
        [RegularExpression(@"^\d{5}(-\d{4})?$", ErrorMessage ="Invalid Zip")]
        public string ZipCode { get; set; }
        public string State { get; set; }
        //public string ImageURL { get; set; }

        public void Persist(ApplicationDbContext context)
        {
            Location location = new Location()
            {
                Name = this.Name,
                Description = this.Description,
                StreetAddress = this.StreetAddress,
                County = this.County,
                ZipCode = this.ZipCode,
                State = this.State
            };
            context.Add(location);
            context.SaveChanges();
        }
    }
}

CoderGirl_StLouisSites/ViewModels/Locations/LocationDetailsViewModel.cs
using CoderGirl_StLouisSites.Data;
using CoderGirl_StLouisSites.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoderGirl_StLouisSites.ViewModels.Locations
{
    public class LocationDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StreetAddress { get; set; }
        public string County { get; set; }
        public string ZipCode { get; set; }
        public string State { get; set; }
        // public List<LocationRateAndReview> RateAndReviews { get; set; }
        public List<int> Ratings { get; set; }
        public List<string> Reviews { get; set; }
        //public string ImageURL { get; set; }

        public static LocationDetailsViewModel GetLocationDetails(int? Id, ApplicationDbContext context)
        {
            if (Id == null)
            {
                return KeyNotFoundException();
            }
         
            Location location = context.Locations.Find(Id);
            List<LocationRateAndReview> locationRateAndReviews = new List<LocationRateAndReview>();
//locationRateAndReview.LocationId = location.Id;
            locationRateAndReviews = context.RateAndReviews.Where(rr => rr.LocationId == Id).ToList();
            //OR
            //List<Models.LocationRateAndReview> rateAndReviews = location.RateAndReviews;
            List<int> ratings = new List<int>();
            List<string> reviews = new List<string>();
            foreach (Models.LocationRateAndReview rr in locationRateAndReviews)
            {
                //extract a rating and a review
                int rate = rr.Rating;
                string review = rr.Review;

                //store it in the list of view model
                
                ratings.Add(rate);
                reviews.Add(review);
            }
            // return the filled list of view model
            return new LocationDetailsViewModel()
            { 
                Id = location.Id,
                Name = location.Name,
                Description = location.Description,
                StreetAddress = location.StreetAddress,
                County = location.County,
                ZipCode = location.ZipCode,
                State = location.State,
                Ratings = ratings,
                Reviews = reviews           
            };
        }

        private static LocationDetailsViewModel KeyNotFoundException()
        {
            throw new NotImplementedException();
        }
    }
}

CoderGirl_StLouisSites/ViewModels/Locations/LocationEditViewModel.cs
using CoderGirl_StLouisSites.Data;
using CoderGirl_StLouisSites.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoderGirl_StLouisSites.ViewModels.Locations
{
    public class LocationEditViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please give description between 2 to 200 characters")][MinLength(2)][StringLength(200)]
        public string Description { get; set; }
        public string StreetAddress { get; set; }
        [Required]
        public string County { get; set; }
        [Required(ErrorMessage = "Zip Code is required")]
        [RegularExpression(@"^\d{5}(-\d{4})?$", ErrorMessage = "Invalid Zip")]
        public string ZipCode { get; set; }
        public string State { get; set; }

        public LocationEditViewModel() { }

        public LocationEditViewModel(int Id, ApplicationDbContext context)
        {
            Location location = context.Locations.Find(Id);
            Name = location.Name;
            Description = location.Description;
            StreetAddress = location.StreetAddress;
            County = location.County;
            ZipCode = location.ZipCode;
            State = location.State;
        }

        public void Persist(int Id, ApplicationDbContext context)
        {
            Location location = new Location()
            {
                Id = Id,
                Name = this.Name,
                Description = this.Description,
                StreetAddress = this.StreetAddress,
                County = this.County,
                ZipCode = this.ZipCode,
                State = this.State
            };
            context.Update(location);
            context.SaveChanges();
        }
    }
}

CoderGirl_StLouisSites/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoderGirl_StLouisSites.Data;
using CoderGirl_StLouisSites.Models;
using CoderGirl_StLouisSites.ViewModels;
using CoderGirl_StLouisSites.ViewModels.Locations;
using Microsoft.AspNetCore.Mvc;

namespace CoderGirl_StLouisSites.Controllers
{
    public class LocationController : Controller
    {
        private ApplicationDbContext context;

        //Dependency Injection; context here is acting like a repository
        //context acting like database
        public LocationController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            //Displaying the list of locations here in Index View
            //List<Location> locations = context.Locations.ToList();
            List<LocationIndexViewModel> locations = LocationIndexViewModel.GetLocationListFromLocation(context);
            return View(locations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(LocationCreateViewModel locationCreateViewModel)
        {
            //CODE BELOW IS WITH MODELS
            //context.Add(location);
            //context.SaveChanges();//After adding SaveChanges puts the changes in the Database

            //CODE BELOW IS WITH VIEWMODELS
            if (!ModelState.IsValid)
            {
                return View(locationCreateViewModel);
            }

            locationCreateViewModel.Persist(context);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            //Location location = context.Locations.Find(Id);
            LocationDetailsViewModel locationViewModel = LocationDetailsViewModel.GetLocationDetails(Id, context);

            return View(locationViewModel);
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            return View(new LocationEditViewModel(Id, context));
        }

        [HttpPost]
        public IActionResult Edit(int Id, LocationEditViewModel locationEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(new LocationEditViewModel(Id, context));
            }

            locationEditViewModel.Persist(Id, context);
            return RedirectToAction(actionName: nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Location location = context.Locations.Find(id);
            context.Locations.Remove(location);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

CoderGirl_StLouisSites/Controllers/LocationRateAndReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoderGirl_StLouisSites.Data;
using CoderGirl_StLouisSites.Models;
using CoderGirl_StLouisSites.ViewModels.LocationRateAndReviews;

namespace CoderGirl_StLouisSites.Controllers
{
    public class LocationRateAndReviewController : Controller
    {
        private readonly ApplicationDbContext context;

        public LocationRateAndReviewController(ApplicationDbContext context)
        {
            this.context = context;
        }

        // GET: LocationRateAndReviews
        public IActionResult Index()
        {

            List<LocationRateAndReview> list = context.RateAndReviews.ToList();
            foreach (LocationRateAndReview item in list)
            {
                int id = item.LocationId;
                Location location = context.Locations.Find(id);
                item.Location = location;
            }
            return View(list);
        }

        // GET: LocationRateAndReviews/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var locationRateAndReview = await context.LocationRateAndReview
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (locationRateAndReview == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(locationRateAndReview);
        //}

        // GET: LocationRateAndReviews/Create
        [HttpGet]
        public IActionResult Create(int locationId)
        {
            //CODE BELOW IS FOR MODELS
            //Location location = context.Locations.Find(locationId);
            //LocationRateAndReview locationRateAndReview = new LocationRateAndReview();
            //locationRateAndReview.LocationId = locationId;
            //locationRateAndReview.Location = location;

            //CODE BELOW IS FOR VIEW MODELS - RESOLVED
            LocationRateAndReviewCreateViewModel locationRateAndReview
                = LocationRateAndReviewCreateViewModel.GetLocationForRateAnReviewFromLocation(locationId, context);

            return View(locationRateAndReview);
        }

        [HttpPost]
        public IActionResult Create(LocationRateAndReviewCreateViewModel locationRateAndReview)
        {
            //CODE BELOW IS FOR MODELS
            //context.Add(locationRateAndReview);
            //context.SaveChanges();

            //CODE BELOW IS THROUGH VIEW MODELS
            locationRateAndReview.Persist(context);
            return RedirectToAction(nameof(Index));
            //return RedirectToAction(controllerName: nameof(Location), actionName: nameof(Index));
        }

        //// POST: LocationRateAndReviews/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Location,Rating,Review")] LocationRateAndReview locationRateAndReview)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        Location location = context.Locations.Find(locationRateAndReview.LocationId);
        //        location.RateAndReviews.Add(locationRateAndReview);

        //        context.Add(locationRateAndReview);
        //        await context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(locationRateAndReview);
        //}

        //// GET: LocationRateAndReviews/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var locationRateAndReview = await context.LocationRateAndReview.FindAsync(id);
        //    if (locationRateAndReview == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(locationRateAndReview);
        //}

        //// POST: LocationRateAndReviews/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,LocationId,Location,Rating,Review")] LocationRateAndReview locationRateAndReview)
        //{
        //    if (id != locationRateAndReview.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            context.Update(locationRateAndReview);
        //            await context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!LocationRateAndReviewExists(locationRateAndReview.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(locationRateAndReview);
        //}

        //// GET: LocationRateAndReviews/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var locationRateAndReview = await context.LocationRateAndReview
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (locationRateAndReview == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(locationRateAndReview);
        //}

        //// POST: LocationRateAndReviews/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var locationRateAndReview = await context.LocationRateAndReview.FindAsync(id);
        //    context.LocationRateAndReview.Remove(locationRateAndReview);
        //    await context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool LocationRateAndReviewExists(int id)
        //{
        //    return context.LocationRateAndReview.Any(e => e.Id == id);
        //}
    }
}

CoderGirl_StLouisSites/Views/Location/Create.cshtml
@model CoderGirl_StLouisSites.ViewModels.Locations.LocationCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center text-info">Create A New Location</h1>

    @*<h4>Location</h4>*@
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label hidden asp-for="Id" class="control-label"></label>
                    <input hidden readonly asp-for="Id" class="form-control" value="0" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                @*Add-Migration to add image object to the Database, Update-Database
                    <div class="form-group">
                        <label asp-for="ImageURL" class="control-label"></label>
                        <input asp-for="ImageURL" class="form-control" />
                        <span asp-validation-for="ImageURL" class="text-danger"></span>
                    </div>
                    *@
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="StreetAddress" class="control-label"></label>
                        <input asp-for="StreetAddress" class="form-control" />
                        <span asp-validation-for="StreetAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="County" class="control-label"></label>
                        <select asp-for="County">
                            <option>St. Louis</option>
                            <option>St. Charles</option>
                            <option>Franklin</option>
                            <option>St. Francois</option>
                            <option>Jefferson</option>
                            <option>Linoln</option>
                            <option>Warren</option>
                            <option>Gasconade</option>
                            <option>Crawford</option>
                            <option>Washington</option>
                            <option>Phelps</option>
                            <option>Ste. Genevieve</option>
                            <option>Iron</option>
                            <option>Pike</option>
                            <option>Reynolds</option>
                            <option>Madison</option>
                            <option>St. Clair</option>
                            <option>Monroe</option>
                            <option>Macoupin</option>
                            <option>Bond</option>
                            <option>Jersey</option>
                            <option>Calhoun</option>
                            <option>Clinton</option>
                            <option>Sullivan</option>
                            <option>Marion</option>
                            <option>Fayette</option>
                        </select>
                        <span asp-validation-for="County" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ZipCode" class="control-label"></label>
                        <input asp-for="ZipCode" class="form-control" />
                        <span asp-validation-for="ZipCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="State" class="control-label"></label>
                        <input asp-for="State" class="form-control text-uppercase" />
                        <span asp-validation-for="State" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

CoderGirl_StLouisSites/Views/Location/Details.cshtml
@model CoderGirl_StLouisSites.ViewModels.Locations.LocationDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h1  class="text-center text-info">Details Of Location</h1>

<div>
    @*<h4 class="text-center text-dark">Location</h4*@
    <div>
        @* @Html.ActionLink("Rate/Review", "Create", "LocationRateAndReview", new { locationId = Model.Id }) |*@
        <a asp-controller="LocationRateAndReview" asp-action="Create" asp-route-locationId="@Model.Id">Rate/Review</a> |
        @*<a asp-controller="Location" asp-action="Edit" asp-route-locationId="@Model.Id">Edit Location</a> |*@
        <a asp-action="Index">Back to List</a>
    </div>
    @*Add-Migration to add image object to the Database, Update-Database
        <section class="LocationImage">
            <img src="@Model.ImageURL" class="align-self-center visible "/>
            <p class="text-center text-info">City Of St.Louis</p>
        </section>
    *@
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StreetAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StreetAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Ratings)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.Ratings)
            {
                <dl>
                    <dd>
                        @item
                    </dd>
                    <hr />
                </dl>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reviews)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.Reviews)
            {
                <dl>
                    <dd>
                        @item
                    </dd>
                    <hr />
                </dl>
            }
        </dd>
    </dl>
</div>

   

CoderGirl_StLouisSites/Views/Location/Edit.cshtml
@model CoderGirl_StLouisSites.ViewModels.Locations.LocationEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center text-info">Edit A Location</h1>

@*<h4>LocationEditViewModel</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StreetAddress" class="control-label"></label>
                <input asp-for="StreetAddress" class="form-control" />
                <span asp-validation-for="StreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="County" class="control-label"></label>
                <select asp-for="County">
                    <option>St. Louis</option>
                    <option>St. Charles</option>
                    <option>Franklin</option>
                    <option>St. Francois</option>
                    <option>Jefferson</option>
                    <option>Linoln</option>
                    <option>Warren</option>
                    <option>Gasconade</option>
                    <option>Crawford</option>
                    <option>Washington</option>
                    <option>Phelps</option>
                    <option>Ste. Genevieve</option>
                    <option>Iron</option>
                    <option>Pike</option>
                    <option>Reynolds</option>
                    <option>Madison</option>
                    <option>St. Clair</option>
                    <option>Monroe</option>
                    <option>Macoupin</option>
                    <option>Bond</option>
                    <option>Jersey</option>
                    <option>Calhoun</option>
                    <option>Clinton</option>
                    <option>Sullivan</option>
                    <option>Marion</option>
                    <option>Fayette</option>
                </select>
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CoderGirl_StLouisSites/Views/Location/Index.cshtml
@model IEnumerable<CoderGirl_StLouisSites.ViewModels.LocationIndexViewModel>

@{
    ViewData["Title"] = "Locations";
}

<h1 class="text-center text-info">List Of All Locations</h1>
<br />

<p>
    <a  asp-action="Create">Create New Location</a>
</p>
<table class="table">
    <thead>
        <tr>
            @* <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AverageRating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
        @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                <a class="text-justify table-hover" asp-controller="Location" asp-action="Details" asp-route-Id="@item.Id">@item.Name</a>
                @*@Html.ActionLink("item.Name", "Details", "Location", new { id = item.Id })*@
                @* @Html.DisplayFor(modelItem => item.Name)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @* USING VIEW MODELS FOR A BETTER ARCHITECTURE<td>*@
                @Html.DisplayFor(modelItem => item.AverageRating)
            </td>
            <td>
                @Html.ActionLink("Rate/Review", "Create", "LocationRateAndReview", new { locationId = item.Id }) |
                @*<a asp-controller="Location" asp-action="Edit" asp-route-locationId="@Model.Id">Edit Location</a>*@
                @Html.ActionLink("Edit", "Edit", "Location", new { Id = item.Id }) |
                @* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("Delete", "Delete", "Location", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>